source "https://rubygems.org"

gem "webrick", "~> 1.8.1"
gem "sassc", "~> 2.4.0"
gem "rouge"
gem "sass-embedded"
gem "public_suffix"
gem "google-protobuf"
gem "jekyll", "~> 4.3.0"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-sass-converter", "~> 3.0"

#gem "html-proofer"
#gem "jekyll-mentions"
#gem "jekyll-coffeescript"
#gem "jekyll-commonmark"
#gem "jekyll-compose"
#gem "jekyll-assets"
#gem "RedCloth"
#gem "kramdown"
#gem "jemoji"
